--1) Leaderboard (run to calculate score for each team):

SELECT COUNT(TeamName) FROM Game 
WHERE LocationID IS NOT NULL;

--2) Used to run the leaderboard query (app runs the leaderboard 
--   query once for each team name in the list generated by this query):

SELECT DISTINCT TeamName FROM Game;

--3) Counts number of teams for display in the leaderboard

SELECT COUNT(DISTINCT TeamName) FROM Game;

--4) Inserts the user-entered team name.

INSERT INTO Game (TeamName) VALUES ('team a');

--5) Inserts the team name and location id into the database
--   when the user scans a qr code. The qr code will be based
--   on a random alphanumeric string.

INSERT INTO Game (LocationID, TeamName) VALUES ('NI39DU3O8E', 'team a');
