--1) Leaderboard (run to calculate score for each team):

SELECT COUNT(LocationID) FROM Game 
WHERE TeamName = 'team a' AND LocationID IS NOT NULL;

--2) Used to run the leaderboard query (app runs the leaderboard 
--   query once for each team name in the list generated by this query):

SELECT DISTINCT TeamName FROM Game;